"""add_original_text_to_notes

Revision ID: 4527e9a75836
Revises: ed37f497192c
Create Date: 2026-04-03 10:44:16.108944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4527e9a75836'
down_revision: Union[str, Sequence[str], None] = 'ed37f497192c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('original_text', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'original_text')
    # ### end Alembic commands ###
