"""add_url_to_images

Revision ID: 733b302355c5
Revises: 4527e9a75836
Create Date: 2026-04-04 11:17:02.365242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733b302355c5'
down_revision: Union[str, Sequence[str], None] = '4527e9a75836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(length=1000), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'url')
    # ### end Alembic commands ###
