"""add_tag_settings

Revision ID: ed37f497192c
Revises: 462ce4e37198
Create Date: 2026-04-03 10:16:20.173340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed37f497192c'
down_revision: Union[str, Sequence[str], None] = '462ce4e37198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('coding_frequency', sa.Integer(), nullable=False),
    sa.Column('coding_times', sa.String(length=100), nullable=False),
    sa.Column('answering_frequency', sa.Integer(), nullable=False),
    sa.Column('answering_times', sa.String(length=100), nullable=False),
    sa.Column('revising_frequency', sa.Integer(), nullable=False),
    sa.Column('revising_times', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_settings')
    # ### end Alembic commands ###
